"""default tariff

Revision ID: 0db17341859a
Revises: 1852409fd74a
Create Date: 2021-03-24 02:47:56.762779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db17341859a'
down_revision = '1852409fd74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('wallet_tariff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wallet', 'wallettariff', ['wallet_tariff_id'], ['id'])
    op.drop_column('wallet', 'limit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('limit', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'wallet_tariff_id')
    # ### end Alembic commands ###
