"""email_not_unique

Revision ID: 5ce18721df7a
Revises: 0db17341859a
Create Date: 2021-03-24 04:00:37.989998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce18721df7a'
down_revision = '0db17341859a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
