"""country_id_nullable

Revision ID: 8043b29e0397
Revises: eff1fe540ba9
Create Date: 2021-03-25 20:27:03.632636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8043b29e0397'
down_revision = 'eff1fe540ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
