"""transfer_transaction_nullable

Revision ID: 812ab366a1ca
Revises: f68dcf7d5636
Create Date: 2021-03-25 10:05:42.812246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812ab366a1ca'
down_revision = 'f68dcf7d5636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
