"""country_table

Revision ID: 8a46cbf0cdfe
Revises: 812ab366a1ca
Create Date: 2021-03-25 20:04:43.932401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a46cbf0cdfe'
down_revision = '812ab366a1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_code', sa.String(length=5), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.add_column('user', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'country_id')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
