"""transfer_transaction

Revision ID: f68dcf7d5636
Revises: 42b66ab83fba
Create Date: 2021-03-25 09:54:55.884540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68dcf7d5636'
down_revision = '42b66ab83fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transfer_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'transaction', ['transfer_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'transfer_transaction_id')
    # ### end Alembic commands ###
